### ISSUE TITLE
pool support Payment Identifier

### ISSUE THREAD

**Issue by sergeyvad** [turtlecoin/node-turtle-pool#32]
are there any plans?

**Comment by brandonlehmann** [comment]
Bounty is currently open for this per #bounties

`200K TURTLECOINS - ADD PAYMENT ID AS A FEATURE IN TURTLECOIN POOL ON GITHUB`

**Comment by brandonlehmann** [comment]
See https://github.com/turtlecoin/node-turtle-pool/tree/paymentid
