### ISSUE TITLE
individual miner hashrate graph is broken on pool miner results page

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/node-turtle-pool#52]
all of the pools running the development branch on Dero Gold are experiencing this

**Comment by brandonlehmann** [comment]
Link please ?

**Comment by brandonlehmann** [comment]
Also any logs of the chart collector would be awesome.

**Comment by ExtraHash** [comment]
https://goldminer.tk/?wallet=dg3dNXWy4mTAwB6S5hs29RCUhTphFe25Z4erY9TYQxBR7gR9C2KaBTcJvAwxvWNxD9gQJRgRAQ7PNN9HJCXnCxBS2L1pGJwcw

http://dyngepeng.zapto.org:85/DEGO/?wallet=dg3dNXWy4mTAwB6S5hs29RCUhTphFe25Z4erY9TYQxBR7gR9C2KaBTcJvAwxvWNxD9gQJRgRAQ7PNN9HJCXnCxBS2L1pGJwcw

i can get more logs later but here's an example of a frequent error i'm getting which may be related

```3|Pool  | 2019-01-09 15:57:01 [api] Stat collection finished: 9 ms redis, 3 ms daemon
3|Pool  | 2019-01-09 15:57:01 [api] Broadcasting to 23 visitors and 21 address lookups
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [api] Error getting user charts data: null
3|Pool  | 2019-01-09 15:57:01 [pool] (Thread 1) Processing block v5.0 share for dg5ANV```

**Comment by brandonlehmann** [comment]
That's very much related.

**Comment by ExtraHash** [comment]
i figured as much, do you need more logs or is that enough? I don't think I"ve seen any other errors related to the chart collector

**Comment by ExtraHash** [comment]
i have weeks worth of logs

**Comment by brandonlehmann** [comment]
Addressed in https://github.com/turtlecoin/node-turtle-pool/commit/6c34b2c228ada442d4f4f0d5807b7a098c96c75a
