### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by deathrace37** [turtlecoin/node-turtle-pool#61]
I have this error:
2020-04-04 03:11:31 [payments] Error with sendTransaction RPC request to wallet daemon {}
2020-04-04 03:11:31 [payments] Payments failed to send to {"amount":218101800,"address":"TRTLv3J6mkP44gVAjuJiJp7JgBLHeqjWqeH9EdzyAqaK3MWyWKSdzg6SK3hafWDLHQ1E283vgUmMbY2Cxc4JX68JaWTBVDYz51r"}

Can you help me please ?

**Comment by brandonlehmann** [comment]
One problem is apparent:  2,181,018.00 TRTL payment to a miner, you sure about that? Something might be a bit off there.

Secondly, do you have turtle-service running?
Thirdly, do you have the proper configuration values loaded in the pool for your running copy of turtle-service?

**Comment by deathrace37** [comment]
I am trying to create my crypto. I am sure the number of TRTLs is correct. I have not yet changed the information on this crypto. I only do tests.

2020-Apr-04 02:54:39.804724 INFO    Program Working Directory: "/root/thenewcoin/build/src"
2020-Apr-04 02:54:39.804996 INFO    Loading Checkpoints for faster initial sync...
2020-Apr-04 02:54:39.805259 INFO    Loaded 0 default checkpoints
2020-Apr-04 02:54:39.805548 INFO    Opening DB in /root/.TurtleCoin/DB
2020-Apr-04 02:54:39.850623 INFO    DB opened in /root/.TurtleCoin/DB
2020-Apr-04 02:54:39.850872 INFO    Initializing core...
2020-Apr-04 02:54:39.852598 INFO    Core initialized OK
2020-Apr-04 02:54:39.852833 INFO    Initializing p2p server...
2020-Apr-04 02:54:39.853065 INFO    Binding on 0.0.0.0:11897
2020-Apr-04 02:54:39.853319 INFO    Net service bound on 0.0.0.0:11897
2020-Apr-04 02:54:39.853454 INFO    Attempting to add IGD port mapping.
2020-Apr-04 02:54:43.857561 INFO    No IGD was found.
2020-Apr-04 02:54:43.857691 INFO    P2p server initialized OK
2020-Apr-04 02:54:43.857736 INFO    Starting core rpc server on address 127.0.0.1:11898
2020-Apr-04 02:54:43.858194 INFO    Starting p2p net loop...
2020-Apr-04 02:54:43.858294 INFO    Starting node_server
2020-Apr-04 02:54:43.860856 INFO    
2020-Apr-04 02:54:43.861874 INFO    ===[ TurtleCoin Tip! ]=============================
2020-Apr-04 02:54:43.862012 INFO     Always exit TurtleCoind and zedwallet with the "exit" command to preserve your chain and wallet data.
2020-Apr-04 02:54:43.862150 INFO     Use the "help" command to see a list of available commands.
2020-Apr-04 02:54:43.862268 INFO     Use the "backup" command in zedwallet to display your keys/seed for restoring a corrupted wallet.
2020-Apr-04 02:54:43.862378 INFO     If you need more assistance, you can contact us for support at http://chat.turtlecoin.lol
2020-Apr-04 02:54:43.862469 INFO    ===================================================
2020-Apr-04 02:54:43.862469 INFO    
2020-Apr-04 02:54:43.862627 INFO    
2020-Apr-04 02:54:43.864829 INFO    New Top Block Detected: 672
2020-Apr-04 02:54:45.866550 INFO    New Top Block Detected: 673
2020-Apr-04 02:54:55.876593 INFO    New Top Block Detected: 674
2020-Apr-04 02:55:03.885033 INFO    New Top Block Detected: 675
2020-Apr-04 02:55:11.892449 INFO    New Top Block Detected: 676
2020-Apr-04 02:55:13.895510 INFO    New Top Block Detected: 677
2020-Apr-04 02:55:33.917509 INFO    New Top Block Detected: 678
2020-Apr-04 02:56:17.971101 INFO    New Top Block Detected: 679
2020-Apr-04 02:56:19.974066 INFO    New Top Block Detected: 680
2020-Apr-04 02:56:29.984559 INFO    New Top Block Detected: 681
2020-Apr-04 02:56:31.987025 INFO    New Top Block Detected: 682

root@vps805347:~/turtle-pool# node init.js
2020-04-04 03:56:36 [master] Pool spawned on 1 thread(s)
2020-04-04 03:56:38 [unlocker] Started
2020-04-04 03:56:38 [charts] Started
2020-04-04 03:56:38 [chartsDataCollector] Started
2020-04-04 03:56:38 [unlocker] No pending blocks are unlocked yet (45 pending)
2020-04-04 03:56:38 [payments] Started
2020-04-04 03:56:38 [charts] Started
2020-04-04 03:56:38 [payments] Using payout level 100000 for worker TRTLv3J6mkP44gVAjuJiJp7JgBLHeqjWqeH9EdzyAqaK3MWyWKSdzg6SK3hafWDLHQ1E283vgUmMbY2Cxc4JX68JaWTBVDYz51r (default: 100000)
2020-04-04 03:56:38 [api] API started & listening on port 8117
2020-04-04 03:56:38 [pool] (Thread 1) New block to mine at height 729 w/ difficulty of 7756
2020-04-04 03:56:38 [api] Stat collection finished: 87 ms redis, 75 ms daemon
2020-04-04 03:56:38 [payments] Error with sendTransaction RPC request to wallet daemon {}
2020-04-04 03:56:38 [payments] Payments failed to send to {"amount":283267200,"address":"TRTLv3J6mkP44gVAjuJiJp7JgBLHeqjWqeH9EdzyAqaK3MWyWKSdzg6SK3hafWDLHQ1E283vgUmMbY2Cxc4JX68JaWTBVDYz51r"}
2020-04-04 03:56:38 [payments] Payments splintered and 0 successfully sent, 1 failed
2020-04-04 03:56:38 [payments] Payments processing failed: null
2020-04-04 03:56:38 [pool] (Thread 1) Started server listening on port 3333
2020-04-04 03:56:38 [api] Broadcasting to 0 visitors and 0 address lookups
2020-04-04 03:56:38 [pool] (Thread 1) Started server listening on port 5555
2020-04-04 03:56:38 [pool] (Thread 1) Started server listening on port 7777
2020-04-04 03:56:38 [pool] (Thread 1) Started server listening on port 8888
2020-04-04 03:56:42 [pool] (Thread 1) Miner connected TRTLv3J6mkP44gVAjuJiJp7JgBLHeqjWqeH9EdzyAqaK3MWyWKSdzg6SK3hafWDLHQ1E283vgUmMbY2Cxc4JX68JaWTBVDYz51r@::ffff:78.222.196.159
2020-04-04 03:56:43 [api] Stat collection finished: 2 ms redis, 16 ms daemon

{
    "coin": "thenewcoin",
    "symbol": "TRTL",
    "coinUnits": 100,
    "coinDifficultyTarget": 30,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

  "poolServer": {
    "enabled": true,
    "clusterForks": "auto",
    "poolAddress": "TRTLv3uXxwq66BXk167m6sNY79QugCovZGHDM9Jkf3dx4mz3C9AVJChDfMK5jqhXWeNC131D4PXsiesP39C9qF4kRMLsmyNhnVs",
    "blockRefreshInterval": 1000,
    "minerTimeout": 3600,
    "ports": [
      {
        "port": 3333,
        "difficulty": 100,
        "desc": "Low end hardware"
      },
      {
        "port": 5555,
        "difficulty": 2000,
        "desc": "Mid range hardware"
      },
      {
        "port": 7777,
        "difficulty": 10000,
        "desc": "High end hardware"
      },
      {
        "port": 8888,
        "difficulty": 10000,
        "desc": "Hidden port",
        "hidden": true
      }
],
    "varDiff": {
      "minDiff": 100,
      "maxDiff": 500000,
      "targetTime": 10,
      "retargetTime": 30,
      "variancePercent": 30,
      "maxJump": 100
    },
    "fixedDiff": {
      "enabled": true,
      "addressSeparator": "."
    },
    "shareTrust": {
      "enabled": true,
      "min": 10,
      "stepDown": 3,
      "threshold": 10,
      "penalty": 30
    },
    "banning": {
 "enabled": true,
      "time": 600,
      "invalidPercent": 25,
      "checkThreshold": 30
    },
    "slushMining": {
      "enabled": false,
      "weight": 120,
      "lastBlockCheckRate": 1
    }
  },

"payments": {
        "enabled": true,
        "interval": 5,
        "maxAddresses": 50,
        "mixin": 3,
        "transferFee": 10,
        "minPayment": 100000,
        "maxTransactionAmount": 0,
        "denomination": 100
    },
"blockUnlocker": {
 "enabled": true,
        "interval": 30,
        "depth": 40,
        "poolFee": 2,
        "devDonation": 0.1,
        "coreDevDonation": 0.1,
        "extraFeaturesDevDonation":0.1
    },
    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "your_password"
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 11898
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 8070,
        "password": "******"
    },
    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getBalance"
        }
 },

    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
 },
            "payments": {
                "enabled": true
            }
        }
    }
}

**Comment by brandonlehmann** [comment]
We do not support the software of forked projects or support using organization repo'd projects on other networks. Would you ask your veterinarian to do your brain surgery?

I've pointed you in the general direction of where you need to look to resolve your problem regarding having the `turtle-service` application running as well.
