### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by wbz7** [turtlecoin/node-turtle-pool#63]
node init.js

2020-09-28 11:07:02 [master] Pool spawned on 1 thread(s)
/home/root1/turtle-pool/node_modules/bindings/bindings.js:99
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/build/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/build/Debug/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/build/Release/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/out/Debug/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/Debug/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/out/Release/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/Release/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/build/default/cryptonote.node
 → /home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/compiled/14.12.0/linux/x64/cryptonote.node
    at bindings (/home/root1/turtle-pool/node_modules/bindings/bindings.js:96:9)
    at Object.<anonymous> (/home/root1/turtle-pool/node_modules/turtlecoin-cryptonote-util/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)

**Comment by wbz7** [comment]
npm update  give 
../src/turtlecoin-crypto.cpp:49:72: error: no matching function for call to ‘v8::Value::ToString()’
 string(*Nan::Utf8String(info[0]->ToString()));
                                           ^
In file included from /home/root1/.cache/node-gyp/14.12.0/include/node/node.h:67:0,
                 from ../node_modules/nan/nan.h:54,
                 from ../src/turtlecoin-crypto.cpp:5:
/home/root1/.cache/node-gyp/14.12.0/include/node/v8.h:2810:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
 WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                       ^~~~~~~~
/home/root1/.cache/node-gyp/14.12.0/include/node/v8.h:2810:44: note:   candidate expects 1 argument, 0 provided
../src/turtlecoin-crypto.cpp: In function ‘void checkSignature(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/turtlecoin-crypto.cpp:82:64: error: no matching function for call to ‘v8::Value::ToString()’
 string(*Nan::Utf8String(info[0]->ToString()));
                                           ^

**Comment by wbz7** [comment]
ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/root1/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-1026-azure
gyp ERR! command "/home/root1/.nvm/versions/node/v14.12.0/bin/node" "/home/root1/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"              gyp ERR! cwd /home/root1/turtle-pool/node_modules/turtlecoin-crypto                             gyp ERR! node -v v14.12.0
gyp ERR! node-gyp -v v5.1.0                     gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: turtlecoin-crypto@1.0.0 (node_modules/turtlecoin-crypto):                                       npm WARN optional SKIPPING OPTIONAL DEPENDENCY: turtlecoin-crypto@1.0.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
                                                + redis@3.0.2
+ safe-buffer@5.2.1                             added 2 packages from 3 contributors, removed 1 package, updated 4 packages and audited 50 packages in 8.059s
                                                2 packages are looking for funding
  run `npm fund` for details

**Comment by brandonlehmann** [comment]
Looks like you didn’t run 'npm install' first

**Comment by brandonlehmann** [comment]
What OS?

**Comment by wbz7** [comment]
> What OS?

ubuntu 
npm install give errors.

**Comment by wbz7** [comment]
> What OS?

can u pm me on diskord? Tokyo#3062 dev channel

**Comment by brandonlehmann** [comment]
As discussed on discord, we do not support forked projects.
